name: Swift CI
on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: debian  # Must match the label in runner-config.yml
    container:
      image: swift:latest
    steps:
      - name: Install dependencies and clone repository
        run: |
          apt-get update && apt-get install -y git make
          git clone https://git.carette.xyz/${GITHUB_REPOSITORY}.git .
          git checkout ${GITHUB_SHA}
          
      - name: Run tests
        run: make run_tests
