name: Swift CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: swift:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Make
        run: apt-get update && apt-get install -y make

      - name: Run tests
        run: make run_tests
